version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - ${DB_PORT}:5432
    networks:
      - default
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      TZ: ${TZ}
      PGTZ: ${TZ}

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    environment:
      PGADMIN_DEFAULT_EMAIL: ${APP_USER}
      PGADMIN_DEFAULT_PASSWORD: ${APP_PASS}

networks:
  default:
    driver: bridge

volumes:
  data:
    driver: local
